# src/export_c.py
"""Export a trained sklearn DecisionTree to portable C (if/else) for on-board inference."""
import argparse
import numpy as np
import joblib
from src.config import FEATURE_NAMES, CLASSES

def py_classify(tree, x):
    """Reference traversal returning the class INDEX (matches sklearn argmax of value)."""
    node = 0
    while tree.children_left[node] != tree.children_right[node]:
        if x[tree.feature[node]] <= tree.threshold[node]:
            node = tree.children_left[node]
        else:
            node = tree.children_right[node]
    return int(np.argmax(tree.value[node][0]))

def tree_to_c(model):
    tree = model.tree_
    classes = list(model.classes_)
    lines = [
        "// Auto-generated by src/export_c.py — do not edit by hand.",
        f"// features: {FEATURE_NAMES}",
        f"// class index -> label: {dict(enumerate(classes))}",
        "int classify(const float f[6]) {",
    ]

    def recurse(node, depth):
        pad = "  " * (depth + 1)
        if tree.children_left[node] == tree.children_right[node]:
            cls = int(np.argmax(tree.value[node][0]))
            lines.append(f"{pad}return {cls};  // {classes[cls]}")
            return
        feat = tree.feature[node]; thr = tree.threshold[node]
        lines.append(f"{pad}if (f[{feat}] <= {thr:.6f}f) {{  // {FEATURE_NAMES[feat]}")
        recurse(tree.children_left[node], depth + 1)
        lines.append(f"{pad}}} else {{")
        recurse(tree.children_right[node], depth + 1)
        lines.append(f"{pad}}}")

    recurse(0, 0)
    lines.append("}")
    return "\n".join(lines)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="model/tree.joblib")
    ap.add_argument("--out", default="model/model.h")
    args = ap.parse_args()
    bundle = joblib.load(args.model)
    code = tree_to_c(bundle["model"])
    with open(args.out, "w") as f:
        f.write(code + "\n")
    print(f"Wrote {args.out}")
